#!/usr/bin/env python3
"""Generate current-value documentation from the source tree.

Writes:
  documentations/enemies-values.md
  documentations/items-values.md

Usage:
  python tools/balance/generate_docs.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

WORKSPACE = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))

import auto_balance as ab  # noqa: E402

DOC_DIR = WORKSPACE / "documentations"
ITEMS_DIR = WORKSPACE / "source/Engine/Items"
ENEMIES_DIR = WORKSPACE / "source/Engine/Entities/Enemies"
DRAWABLES_XML = WORKSPACE / "resources/drawables/drawables.xml"
REPORT_JSON = WORKSPACE / "tools/balance/balance_report.json"

GENERATED_NOTE = (
    "> Auto-generated by `tools/balance/generate_docs.py` from the source tree"
    " + `tools/balance/balance_report.json`. Do not edit manually;"
    " regenerate after balance changes with `python tools/balance/generate_docs.py`."
)

TIER_NAMES = {
    0: "Steel", 1: "Bronze", 2: "Fire", 3: "Ice", 4: "Grass",
    5: "Water", 6: "Gold", 7: "Demon", 8: "Blood",
}

ATTR_SHORT = {
    "strength": "STR", "dexterity": "DEX", "intelligence": "INT",
    "constitution": "CON", "wisdom": "WIS", "charisma": "CHA",
}
ATTR_ORDER = ["strength", "dexterity", "intelligence", "constitution", "wisdom", "charisma"]
TYPE_SHORT = {
    "STRENGTH": "STR", "DEXTERITY": "DEX", "INTELLIGENCE": "INT",
    "CONSTITUTION": "CON", "WISDOM": "WIS", "CHARISMA": "CHA",
}

ENEMY_SECTIONS = [
    ("Easy", "## Easy (early depths)"),
    ("Easy/Elementals", "## Small Elementals (early depths)"),
    ("Normal", "## Normal (mid depths)"),
    ("Normal/Elementals", "## Elementals (mid-late depths)"),
    ("Hard", "## Hard (late depths)"),
    ("Custom", "## Custom"),
    ("Bosses", "## Bosses (not spawned)"),
]

FIXED_ITEM_GROUPS = [
    ("WeaponItems/Crossbow", "## Crossbows"),
    ("WeaponItems/Ammunition", "## Ammunition"),
    ("ArmorItems/Shield", "## Shields"),
    ("ArmorItems/Backpack", "## Backpacks"),
    ("ArmorItems", "## Amulets & Accessories"),
    ("Custom/WeaponItems", "## Custom Items"),
    ("ConsumableItems", "## Consumables"),
    ("SpecialItems", "## Special Items"),
]


def load_drawables() -> Dict[str, str]:
    text = DRAWABLES_XML.read_text(encoding="utf-8", errors="replace")
    return dict(re.findall(r'<bitmap id="([^"]+)" filename="([^"]+)"', text))


def img_cell(sprite: Optional[str], dmap: Dict[str, str], width: int = 32) -> str:
    if not sprite or sprite not in dmap:
        return "-"
    filename = dmap[sprite]
    return f'<img src="../resources/drawables/{filename}" width="{width}" alt="{sprite}">'


def get_sprite(text: str) -> Optional[str]:
    m = re.search(r"function getSprite.*?return\s+\$\.Rez\.Drawables\.(\w+)", text, re.S)
    return m.group(1) if m else None


def init_body(text: str) -> str:
    return ab.extract_function_body(text, "initialize") or ""


def quoted(body: str, text: str, key: str) -> str:
    m = re.search(rf'(?:self\.)?{key}\s*=\s*"([^"]*)"', body)
    if not m:
        m = re.search(rf'var\s+{key}\s+as\s+\w+\s*(?:\?\s*)?=\s*"([^"]*)"', text)
    return m.group(1) if m else ""


def parse_weight(body: str, text: str) -> Optional[float]:
    m = re.search(rf"(?:self\.)?weight\s*=\s*([0-9.]+)", body)
    if not m:
        m = re.search(rf"var\s+weight\s+as\s+\w+\s*=\s*([0-9.]+)", text)
    return float(m.group(1)) if m else None


def fmt_num(v) -> str:
    if v is None:
        return "-"
    if isinstance(v, float):
        return str(int(v)) if v.is_integer() else f"{v:g}"
    return str(v)


def bonus_text(bonus: Dict[str, int]) -> str:
    if not bonus:
        return "-"
    parts = [f"{ATTR_SHORT.get(k, k)}{bonus[k]:+d}" for k in ATTR_ORDER if k in bonus]
    parts += [
        f"{ATTR_SHORT.get(k, k)}{v:+d}"
        for k, v in sorted(bonus.items())
        if k not in ATTR_ORDER
    ]
    return " ".join(parts)


def source_link(path: Path) -> str:
    return "../" + path.relative_to(WORKSPACE).as_posix()


def write_doc(name: str, text: str) -> None:
    path = DOC_DIR / name
    try:
        path.write_text(text, encoding="utf-8", newline="\n")
    except TypeError:
        path.write_text(text, encoding="utf-8")
    print(f"wrote {path.relative_to(WORKSPACE)} ({len(text.splitlines())} lines)")


# --------------------------------------------------------------------------
# Enemies
# --------------------------------------------------------------------------

def build_enemies_doc(dmap: Dict[str, str]) -> str:
    enemies = ab.parse_enemy_files(WORKSPACE)
    weights = ab.parse_enemy_weights(WORKSPACE)
    report = json.loads(REPORT_JSON.read_text(encoding="utf-8"))
    config = report["config"]
    depth_win = {int(k): v["actualWinRate"] for k, v in report["depthResults"].items()}
    depth_tgt = {int(k): v["targetWinRate"] for k, v in report["depthResults"].items()}
    tol = float(config.get("tolerance", 0.05))

    lines: List[str] = [
        "# Enemy Values",
        "",
        "Current enemy stats, spawn tables and balance status.",
        "",
        GENERATED_NOTE,
        "",
        "## Roster",
        "",
        "Base stats at depth 1. Scaling with depth (`Enemy.setLevel`):",
        "`stat x (1 + (depth - 1) x scale)` with the scales from"
        " `enemyDepthScaling` (see Balance Status below).",
        "",
        "`Period` is the effective attack period in turns"
        " (energy gating + attack cooldown, lower = attacks more often).",
        "",
    ]

    groups: Dict[str, List[int]] = {}
    for eid, e in enemies.items():
        rel = e.file.relative_to(ENEMIES_DIR)
        group = rel.parent.as_posix()
        groups.setdefault(group, []).append(eid)

    ordered = [g for g, _ in ENEMY_SECTIONS if g in groups]
    ordered += sorted(g for g in groups if g not in dict(ENEMY_SECTIONS))
    for group in ordered:
        title = dict(ENEMY_SECTIONS).get(group, f"## {group}")
        lines += [
            title,
            "",
            "| Image | ID | Enemy | HP | Damage | Armor | XP | Period |",
            "|---|---:|---|---:|---:|---:|---:|---:|",
        ]
        for eid in sorted(groups[group]):
            e = enemies[eid]
            sprite = get_sprite(e.file.read_text(encoding="utf-8", errors="replace"))
            lines.append(
                f"| {img_cell(sprite, dmap)} | {eid} | {e.name} | {e.max_health} |"
                f" {e.damage} | {e.armor} | {e.kill_experience} | {e.attack_cooldown} |"
            )
        lines.append("")

    # Spawn weights
    if weights:
        tier_maxes = sorted({int(t) for entry in weights for t, _ in entry["tiers"]})  # type: ignore[index]
        lines += [
            "## Enemy Spawn Weights",
            "",
            "Current `:cost` / `:weight` tables from `EnemySpecificValues.mc`"
            " (weight for depth tier).",
            "",
            "| Enemy | Cost | " + " | ".join(f"<= {m}" for m in tier_maxes) + " |",
            "|---|---:|" + "---:|" * len(tier_maxes),
        ]

        def weight_at(tiers: List[Tuple[int, float]], depth: int) -> float:
            for tier_max, weight in tiers:
                if depth <= tier_max:
                    return weight
            return tiers[-1][1]

        def fmt_w(v: float) -> str:
            return str(int(v)) if float(v).is_integer() else f"{v:g}"

        for entry in sorted(weights, key=lambda x: int(x["id"])):  # type: ignore[arg-type]
            eid = int(entry["id"])  # type: ignore[arg-type]
            name = enemies[eid].name if eid in enemies else str(eid)
            tiers: List[Tuple[int, float]] = entry["tiers"]  # type: ignore[assignment]
            cells = " | ".join(fmt_w(weight_at(tiers, m)) for m in tier_maxes)
            lines.append(f"| {name} | {entry['cost']} | {cells} |")  # type: ignore[index]
        lines.append("")

    # Balance status
    lines += ["## Balance Status", ""]
    lines += [
        "From `tools/balance/balance_report.json` (last simulator run).",
        "",
        "| Key | Value |",
        "|---|---|",
        f"| Tolerance | +/- {tol} |",
        f"| Rounds per depth | {config.get('roundsPerDepth')} |",
        f"| Strict realism | {config.get('strictRealism')} |",
    ]
    room_size = config.get("roomSizeRange")
    if isinstance(room_size, dict):
        room_text = f"{room_size.get('min')}-{room_size.get('max')}"
    else:
        room_text = str(room_size)
    lines += [
        f"| Room size range | {room_text} |",
        f"| Rooms per depth (progression) | {config.get('roomsPerDepthForProgression')} |",
        f"| Initial attribute points | {config.get('initialAttributePoints')} |",
        "",
        "### Depth Scaling (`enemyDepthScaling`)",
        "",
        "| Stat | Scale |",
        "|---|---:|",
    ]
    scaling = config.get("enemyDepthScaling") or {}
    if isinstance(scaling, dict):
        for key, label in (
            ("healthScale", "Health"),
            ("damageScale", "Damage"),
            ("armorScale", "Armor"),
            ("xpScale", "Kill XP"),
        ):
            if key in scaling:
                lines.append(f"| {label} | {scaling[key]} |")

    targets = config.get("targetWinRateByDepth") or []
    if targets:
        lines += ["", "### Target Win Rates", "", "| Depths | Target |", "|---|---:|"]
        prev = 0
        for entry in targets:  # type: ignore[union-attr]
            max_d = int(entry["maxDepth"])  # type: ignore[index]
            target = float(entry["target"])  # type: ignore[index]
            lo, hi = prev + 1, max_d
            depth_label = str(lo) if lo == hi else f"{lo}-{hi}"
            lines.append(f"| {depth_label} | {target:.0%} |")
            prev = max_d

    def seg_stats(dmin: int, dmax: int) -> Tuple[float, float, int]:
        vals = [(depth_win[d], depth_tgt[d]) for d in depth_win if dmin <= d <= dmax and d in depth_tgt]
        if not vals:
            return 0.0, 0.0, 0
        avg_a = sum(a for a, _ in vals) / len(vals)
        avg_t = sum(t for _, t in vals) / len(vals)
        outside = sum(1 for a, t in vals if abs(a - t) > tol)
        return avg_a, avg_t, outside

    lines += ["", "### Depth Segments", ""]
    for name, dmin, dmax in (
        ("Early (1-25)", 1, 25),
        ("Mid (26-100)", 26, 100),
        ("Late (101-150)", 101, 150),
        ("Endgame (151-200)", 151, 200),
    ):
        avg_a, avg_t, outside = seg_stats(dmin, dmax)
        delta = avg_a - avg_t
        status = "ok" if abs(delta) <= tol else ("too easy" if delta > 0 else "too hard")
        lines.append(
            f"- **{name}**: {avg_a:.1%} (target {avg_t:.1%}, {delta:+.1%}) [{status}]"
            f" - {outside} depth(s) outside +/- {tol:g}"
        )

    outside_depths = sorted(
        d for d in depth_win if d in depth_tgt and abs(depth_win[d] - depth_tgt[d]) > tol
    )
    lines += ["", f"### Depths Outside Tolerance ({len(outside_depths)}/{len(depth_win)})", ""]
    if outside_depths:
        runs: List[List[int]] = []
        for d in outside_depths:
            if runs and d == runs[-1][-1] + 1:
                runs[-1].append(d)
            else:
                runs.append([d])
        for run in runs:
            details = " ".join(
                f"d{d}={depth_win[d]:.2f}({depth_win[d] - depth_tgt[d]:+.2f})" for d in run
            )
            label = f"d{run[0]}" if len(run) == 1 else f"d{run[0]}-{run[-1]}"
            lines.append(f"- {label}: {details}")
        lines.append("")
        lines.append("Full depth table: `tools/balance/balance_report.md`.")
    else:
        lines.append("All depths within tolerance.")

    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Items
# --------------------------------------------------------------------------

def parse_consumables() -> List[Dict[str, object]]:
    out = []
    for path in sorted(ITEMS_DIR.rglob("*.mc")):
        text = path.read_text(encoding="utf-8", errors="replace")
        m = re.search(r"class\s+(\w+)\s+extends\s+(\w+)", text)
        if not m or m.group(2) != "ConsumableItem":
            continue
        body = init_body(text)
        idm = re.search(r"(?:self\.)?id\s*=\s*(\d+)", body) or re.search(
            r"var\s+id\s+as\s+\w+\s*=\s*(\d+)", text
        )
        if not idm:
            continue
        out.append({
            "id": int(idm.group(1)),
            "class_name": m.group(1),
            "file": path,
            "name": quoted(body, text, "name") or m.group(1),
            "description": quoted(body, text, "description"),
            "effect": quoted(body, text, "effect_description"),
            "value": ab.parse_number_assignment(body, "value", 0),
            "weight": parse_weight(body, text),
            "sprite": get_sprite(text),
        })
    return out


def parse_specials() -> List[Dict[str, object]]:
    out = []
    for path in sorted((ITEMS_DIR / "SpecialItems").rglob("*.mc")):
        text = path.read_text(encoding="utf-8", errors="replace")
        m = re.search(r"class\s+(\w+)\s+extends\s+(\w+)", text)
        if not m:
            continue
        body = init_body(text)
        idm = re.search(r"var\s+id\s+as\s+\w+\s*=\s*(\d+)", text) or re.search(
            r"(?:self\.)?id\s*=\s*(\d+)", body
        )
        if not idm:
            continue
        out.append({
            "id": int(idm.group(1)),
            "class_name": m.group(1),
            "file": path,
            "name": quoted(body, text, "name") or m.group(1),
            "description": quoted(body, text, "description"),
            "value": ab.parse_number_assignment(body, "value", 0),
            "weight": parse_weight(body, text),
            "sprite": get_sprite(text),
        })
    return out


def item_extras(item) -> Dict[str, object]:
    text = item.file.read_text(encoding="utf-8", errors="replace")
    body = init_body(text)
    return {
        "name": quoted(body, text, "name") or item.class_name,
        "description": quoted(body, text, "description"),
        "weight": parse_weight(body, text),
        "slot": (lambda m: m.group(1) if m else None)(re.search(r"(?:self\.)?slot\s*=\s*(\w+)", body)),
        "sprite": get_sprite(text),
    }


def weapon_table(items, dmap: Dict[str, str]) -> List[str]:
    lines = [
        "| Image | Item | ID | Attack | Scales | Value | Weight | Bonus |",
        "|---|---|---:|---:|---|---:|---:|---|",
    ]
    for iid, item, extra in sorted(items, key=lambda x: x[0]):
        name = str(extra["name"])
        link = f"[{name}]({source_link(item.file)})"
        lines.append(
            f"| {img_cell(extra['sprite'], dmap)} | {link} | {iid} | {item.attack} |"
            f" {TYPE_SHORT.get(item.attack_type, item.attack_type)} | {item.value} |"
            f" {fmt_num(extra['weight'])} | {bonus_text(item.attribute_bonus)} |"
        )
    return lines


def armor_table(items, dmap: Dict[str, str]) -> List[str]:
    lines = [
        "| Image | Item | ID | Defense | Slot | Scales | Value | Weight | Bonus |",
        "|---|---|---:|---:|---|---|---:|---:|---|",
    ]
    for iid, item, extra in sorted(items, key=lambda x: x[0]):
        name = str(extra["name"])
        link = f"[{name}]({source_link(item.file)})"
        slot = extra["slot"] or "-"
        lines.append(
            f"| {img_cell(extra['sprite'], dmap)} | {link} | {iid} | {item.defense} |"
            f" {slot} | {TYPE_SHORT.get(item.defense_type, item.defense_type)} |"
            f" {item.value} | {fmt_num(extra['weight'])} | {bonus_text(item.attribute_bonus)} |"
        )
    return lines


def build_items_doc(dmap: Dict[str, str]) -> str:
    by_class, _by_id = ab.parse_item_files(WORKSPACE)
    consumables = parse_consumables()
    specials = parse_specials()

    lines: List[str] = [
        "# Item Values",
        "",
        "Current item stats, sprites and drop tables.",
        "",
        GENERATED_NOTE,
        "",
        "`Scales` is the attribute the stat scales with"
        " (`Attack` for weapons, `Defense` for armor).",
        "`Bonus` lists flat attribute bonuses from `attribute_bonus`.",
        "",
    ]

    # Group items by source folder
    groups: Dict[str, List] = {}
    for item in by_class.values():
        rel = item.file.relative_to(ITEMS_DIR)
        groups.setdefault(rel.parent.as_posix(), []).append(item)

    # Weapons by tier
    tier_folders = sorted(
        (k for k in groups if re.fullmatch(r"WeaponItems/\d+_\w+", k)),
        key=lambda k: int(k.split("/")[1].split("_")[0]),
    )
    if tier_folders:
        lines += ["## Weapons", ""]
        for key in tier_folders:
            n = int(key.split("/")[1].split("_")[0])
            rows = [(i.id, i, item_extras(i)) for i in groups[key]]
            lines += [f"### Tier {n}: {TIER_NAMES.get(n, '?')}", ""]
            lines += weapon_table(rows, dmap)
            lines.append("")

    # Armor by tier
    armor_folders = sorted(
        (k for k in groups if re.fullmatch(r"ArmorItems/Armors/\d+_\w+", k)),
        key=lambda k: int(k.split("/")[2].split("_")[0]),
    )
    if armor_folders:
        lines += ["## Armor", ""]
        for key in armor_folders:
            n = int(key.split("/")[2].split("_")[0])
            rows = [(i.id, i, item_extras(i)) for i in groups[key]]
            lines += [f"### Tier {n}: {TIER_NAMES.get(n, '?')}", ""]
            lines += armor_table(rows, dmap)
            lines.append("")

    # Fixed groups (shields, backpacks, ammo, ...)
    for key, title in FIXED_ITEM_GROUPS:
        if key not in groups:
            continue
        rows = [(i.id, i, item_extras(i)) for i in groups[key]]
        is_armor = key.startswith("ArmorItems")
        lines += [title, ""]
        lines += armor_table(rows, dmap) if is_armor else weapon_table(rows, dmap)
        lines.append("")

    # Any unknown folders
    known = set(tier_folders) | set(armor_folders) | {k for k, _ in FIXED_ITEM_GROUPS}
    for key in sorted(set(groups) - known):
        rows = [(i.id, i, item_extras(i)) for i in groups[key]]
        is_armor = rows[0][1].kind == "armor"
        lines += [f"## {key}", ""]
        lines += armor_table(rows, dmap) if is_armor else weapon_table(rows, dmap)
        lines.append("")

    # Consumables
    if consumables:
        lines += [
            "## Consumables",
            "",
            "| Image | Item | ID | Effect | Value | Weight |",
            "|---|---|---:|---|---:|---:|",
        ]
        for c in sorted(consumables, key=lambda x: x["id"]):  # type: ignore[var-annotated]
            name = str(c["name"])
            link = f"[{name}]({source_link(c['file'])})"  # type: ignore[arg-type]
            effect = str(c["effect"]) or str(c["description"])
            lines.append(
                f"| {img_cell(c['sprite'], dmap)} | {link} | {c['id']} | {effect} |"
                f" {c['value']} | {fmt_num(c['weight'])} |"
            )
        lines.append("")

    # Special items
    if specials:
        lines += [
            "## Special Items",
            "",
            "| Image | Item | ID | Description | Value | Weight |",
            "|---|---|---:|---|---:|---:|",
        ]
        for c in sorted(specials, key=lambda x: x["id"]):  # type: ignore[var-annotated]
            name = str(c["name"])
            link = f"[{name}]({source_link(c['file'])})"  # type: ignore[arg-type]
            lines.append(
                f"| {img_cell(c['sprite'], dmap)} | {link} | {c['id']} |"
                f" {c['description']} | {c['value']} | {fmt_num(c['weight'])} |"
            )
        lines.append("")

    # Drop weights
    tables = ab.parse_item_weight_tables(WORKSPACE)
    bodies = tables.method_bodies
    consumable_body = bodies.get("buildConsumableWeights", "")
    cross_tiers = ab.parse_item_inline_tiers(consumable_body)
    weight_sections = [
        ("Weapons", bodies.get("buildWeaponWeights", "")),
        ("Armor", bodies.get("buildArmorWeights", "")),
        ("Consumables", consumable_body),
        ("High Quality", bodies.get("buildHighQualityWeights", "")),
        ("Merchant", bodies.get("buildMerchantWeights", "")),
    ]
    rendered = False
    for title, body in weight_sections:
        rows = ab.parse_item_weight_report(body, cross_tiers=cross_tiers)
        if not rows:
            continue
        if not rendered:
            lines += [
                "## Item Drop Weights",
                "",
                "Current tiered drop weights from `ItemSpecificValues.mc`"
                " (`build*Weights`).",
                "",
            ]
            rendered = True
        lines += [
            f"### {title}",
            "",
            "| Weight | Item IDs | Tiers (depth <= max: weight) |",
            "|---|---|---|",
        ]
        for display, ids, tiers_text in rows:
            lines.append(f"| {display} | {', '.join(str(i) for i in ids)} | {tiers_text} |")
        lines.append("")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    DOC_DIR.mkdir(parents=True, exist_ok=True)
    dmap = load_drawables()
    write_doc("enemies-values.md", build_enemies_doc(dmap))
    write_doc("items-values.md", build_items_doc(dmap))


if __name__ == "__main__":
    main()
